version: '3'
services:
  tomcat:
    image: tomcat
    container_name: tomcat
    ports:
      - '8080:8080'
    volumes:
      - ~/Desktop/webapps:/usr/local/tomcat/webapps
networks:
  default:
    external:
      name: docker-network