version:

services:

postgres:

  image: postgres
  container_name: postgres
  ports:
    - '5432:5432'
  environment:
    - POSTGRES_PASSWORD=password
  volumes:
    - postgres-data:/var/lib/postgresql/data

network:

  default:

  external:

  name: docker-network

