version: '3'
services:
  nginx:
  image: nginx
  container_name: nginx2
  ports:
  - '8092:80'
  volumes:
  - ./conf/nginx.conf:etc/nginx/nginx.conf:ro
networks:
  default:
  external:
  name: docker-network


  ⚠️语法错误




