version:'3'

services:

  nginx:

  image:nginx

  container_name:nginx

  ports:

  -'8080:80'

  volumes:

  - .:/usr/share/nginx/html:ro

  - .:/nginx.conf:etc/nginx/nginx.conf:ro

networks:

  default:

  external:

  name:docker-network




