version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    command: [
      "--log-bin=mysql-bin",
      "--server-id=1"
    ]
volumes:
  mysql-data:
networks:
  default:
    external:
      name: docker-network